### ISSUE TITLE
C14-2 As a System i should be able to calculate the QualityIndex of the post

### ISSUE THREAD

**Issue by BeshoyAtef** [DinaSaad/sharesoft-13#100]
Success:
User Posted his post, and the system automatically calculated his post quality index

Failure:
System get fooled by fake information thus gives a high quality index that doest reflect the info on the post

Reviewers:
Documentation Reviewer @Tharwat7 
UML/Design Reviewer @HalaKamal 
Implementation Reviewer @mohamedahmedawad93 
Scenario Reviewer @AbdelrahmanAyad 

Tasks:
C1.14-2.1 -Unit Tests
C4.14-2.2 - Implementation 
C4.14-2.3 - Documentation 
C4.14-2.4 - User Interface
C4.14-2.5 - Sequence Diagram

**Comment by HalaKamal** [comment]
the same comment rewrite the boxes in the right form , then the views what its doing loop or if conditions specify please in right form ,

**Comment by BeshoyAtef** [comment]
@mohamedahmedawad93 Please Check my Code
