### ISSUE TITLE
As a User i should be able to report some Posts

### ISSUE THREAD

**Issue by Tharwat7** [DinaSaad/sharesoft-13#101]
Success:
User could identify and report a certain post and report it

Failure:
User report a wrong post/ or fails to get a response to his report.  Admin is not logged in yet is able to report a post 

Reviewers:
Documentation Reviewer @mahmoudHussein 
UML/Design Reviewer @HalaKamal 
Code Reviewer @BeshoSmile  
Scenario Reviewer @AbdelrahmanAyad 

Tasks:
C1-17

**Comment by HalaKamal** [comment]
first the life time of the user must be upper than the other life times, and there must be life times in the third box, rewrite the boxes names correctly as systems and ul  and there must be a render to the user

**Comment by HalaKamal** [comment]
and export the uml not snapshots
