### ISSUE TITLE
As a System i should identify the state of the Post (based on the date and the state)

### ISSUE THREAD

**Issue by Tharwat7** [DinaSaad/sharesoft-13#102]
Success:
Post has four states ( new , sold , archived, unsold  ). Admin defines the time span of the channel until the post is old and then archived ,  the new post is previewed in the home page with a ribbon on the post , 

[*A post has three possible statuses wether sold or unsold (new, old and archived).
*The webmaster defines the timeout required for posts to go from New status to Old status, or from Old to Archived.
*A new post will be represented by a ribbon on the post.]"

Failure:
[*No user involvement]

Reviewers:
Documentation Reviewer @Tharwat7  
UML/Design Reviewer @HalaKamal 
Code Reviewer @BeshoSmile  
Scenario Reviewer @AbdelrahmanAyad 
@mahmoudHussein 
Tasks:
C1-11

**Comment by BeshoyAtef** [comment]
:+1:

**Comment by Tharwat7** [comment]
@abdelrahmanMaged @BeshoSmile @HalaKamal @mahmoudHussein 

please review my code :)

**Comment by BeshoyAtef** [comment]
Merged !!
