### ISSUE TITLE
As c3 , (a system) I should be able to provide a refinement bar along while previewing the posts 

### ISSUE THREAD

**Issue by Reem-Sharkawy** [DinaSaad/sharesoft-13#103]
Success:
first time , the user will find al the channels and sub channels clicked ad they appear in the hom epage , user starts to unclick a sub-channel or a channel to match his interests . the posts are refined or updated each time the user clicks or unclicks a channel or a sub-channel 

Failure:
user unclicks all channels and subchannels , he will be displayed a message to choose a subchannel to view posts from , and he will be given a link to be redirected to the advanced search page according to his will .

Reviewers:
Documentation Reviewer @saraismail1234 
UML/Design Reviewer @iBebarz  
Implementation Reviewer @mohamedhammad89 
Scenario Reviewer @nadeembarakat 

Tasks:
C3.8.1 -Unit Tests
C3.8.2 Implementation 
C3.8.3 Documentation 
C3.8.4 User Interface
C3.8.5 Sequence Diagram

**Comment by BeshoyAtef** [comment]
@Reem-Sharkawy  Please Check you mail for the Issue format that must be followed
