### ISSUE TITLE
C1-14 As a System i should be able to promote the quality of the posts 

### ISSUE THREAD

**Issue by BeshoyAtef** [DinaSaad/sharesoft-13#105]
Success:
System promotes posts according to its quality/the system will calculate the quality of the post based on the weight of the attributes that are defined by the Admin  
[The user can track a post's progress by sorting the posts by quality.]

Failure:
User fails to acknowledge the required attributes needed to be fulfilled in order to increase the quality of his post(to be promoted) ,and in the profile page a small rectangular box at the top of the page with a msg"Please review your post and fill more info to promote your post to reach more users"

Reviewers:
Documentation Reviewer @Tharwat7 
UML/Design Reviewer @HalaKamal 
Implementation Reviewer @mohamedahmedawad93 
Scenario Reviewer @AbdelrahmanAyad 

Tasks:
C1.14.1 -Unit Tests
C4.14.2 - Implementation 
C4.14.3 - Documentation 
C4.14.4 - User Interface
C4.14.5 - Sequence Diagram

**Comment by AbdelrahmanAyad** [comment]
beshoy in the branch named cal_quality index there is a code error so the project does not validate hence i can not run the server please check it so i can perform my task, regards

**Comment by HalaKamal** [comment]
@BeshoSmile  besho your diagram has some things must be done, first the box must has the <<UI>> up and index.html down , and the views.py must has up of it <<System>>, and there must be loop box remake it again
