### ISSUE TITLE
C1-10  As a User i can comment on Posts: [User commenting on a Post]

### ISSUE THREAD

**Issue by HalaKamal** [DinaSaad/sharesoft-13#107]
SUCCESS:
as a user I should be logged in , the post is in the home page , user presses " more details ie, button" , user gets directed to the post's main page , user find a text box to write his commenta and a submit button , user's comment is posted below other user's comments , user is notified that his comment is added

[A logged in user:
*Post in the Home page on which the user wants to comment
*In the Post Preview, user presses "More details" button
*User gets redirected to the "Post main page" where there is a text box for comment input
*After comment entry, user presses the "Submit" button (will be solidified unless the comment field has some text), then user's comment gets posted below the other users' comments
*User gets notified that his comment is added]
[The user can track a post's progress by sorting the posts by quality.]

FAILURE:
as long as the text box is empty , the comment button is grey and is unclickable until one characcter is entered , if a user is a guest or an unverified user he can still go with the same procedure as logged user except that when he tries to comment , he will be notified that he's not logged in and a hyper link will redirect him to a login page

[*User fails to understand that to "comment on a post" he has to open the post through the "more details" button.
*User leaves the comment field empty.
*User forgets to press the "Submit" button.]

Reviewers:
Documentation Reviewer @Tharwat7
UML/Design Reviewer @HalaKamal
Implementation Reviewer @mohamedahmedawad93
Scenario Reviewer @AbdelrahmanAyad

Tasks:
C1.10.1 -Unit Tests
C4.11.2 - Implementation
C4.12.3 - Documentation
C4.13.4 - User Interface

**Comment by Tharwat7** [comment]
@HalaKamal please link your commits to the issues :)

**Comment by BeshoyAtef** [comment]
please Check my comments 

the code dont compile
