### ISSUE TITLE
c2-16 As an admin, i should be abl to manage posts and remove inappropriate ones (hide as a function)

### ISSUE THREAD

**Issue by HalaKamal** [DinaSaad/sharesoft-13#108]
SUCCESS:
admin being abl to check the posts and remove inappropriate one , admin is able to navigate to the reported post , and is able to approve(hide) or reject the report ( do nothing)

FAILURE:
admin can not have access to other users' content or removing inappropriate posts , reports are not delivered to the admin , admin canot remove the post 

Reviewers:
Documentation Reviewer @Tharwat7
UML/Design Reviewer @HalaKamal
Implementation Reviewer @mohamedahmedawad93
Scenario Reviewer @AbdelrahmanAyad

Tasks:
C2.16.1 -Unit Tests
C2.16.2 - Implementation
C2.16.3 - Documentation
C2.16.4 - User Interface
C2.16.5 - Sequence Diagram

**Comment by HalaKamal** [comment]
i finished searching and i'm coding

**Comment by HalaKamal** [comment]
i finished all searching .coding, uml, documentation

**Comment by Tharwat7** [comment]
@HalaKamal please link your commits to the issue :)

**Comment by abdelrahmanMaged** [comment]
@Tharwat7 @BeshoSmile  kindly be notified that the story has been reshuffled for me so i will  modify hala's backend and create the front end and tests.

**Comment by BeshoyAtef** [comment]
:+1:

**Comment by abdelrahmanMaged** [comment]
@HalaKamal  please review the uml it has been 2 hours online
