### ISSUE TITLE
as a buyer/seller i should be able to share posts through facebook and twitter

### ISSUE THREAD

**Issue by saraismail1234** [DinaSaad/sharesoft-13#109]
Success: 
- if the user is logged in with facebook , the user click on share , a pop up box appears for the user to add words before   sharing , if not connected to facebook , a pop up box appears to log in through facebook with facebook email and  password , the user's email and password is saved in the database for later is the user needs at any time to share again   any post.

Failure:
- user is not logged in , and tries to share , he will be provided a link to sign in through facebook / user doesnot have a facebook account , he will be provided a link also to sign up to facebook in the same pop up box that will direct him to the sign up page at facebook , then he will navigate to the post and start to share smoothly.

Reviewers:
- senario reviewers @Reem-Sharkawy and @nadeembarakat 
- code reviewer @mohamedhammad89 
- UML reviewer @iBebarz 

Tasks:
- C3-19.1: search for how sharing through facebook is done.
- C3-19.2: implement it, and coordinate with the facebook connection.
- C3-19.3: test it.

**Comment by BeshoyAtef** [comment]
@saraismail1234 Pleas Read your mail for a correct issue content format

**Comment by Reem-Sharkawy** [comment]
sara the label is already reopened , however you need to figure out how to link the sharing with the post
