### ISSUE TITLE
as a buyer/seller i shoild be able to subscribe to channels or subchannels or by patameters and get notifications about these subscriptions

### ISSUE THREAD

**Issue by mohamedahmedawad93** [DinaSaad/sharesoft-13#110]
@maizaied @mahmoudHussein @HebaElSobky 
success : 
user gets the posts he had subscribed in successfully and receive notifications about his subscriptions successfully

failure : 
user doesn't receive the posts he has subscribed in and getting a notification about a wrong channel that was not subscribed to, not receiving notifications about any updates about the subscribed channel

tasks:
1-searching about writing tests in python
2-write my test code
3-brain storming to make optimized and efficient database tables and queries
4-as a user i should receive posts that i have subscribed into
5-as a user i should receive notifications about my subscriptions
6-make my templates and views
7-test my code
8-document my work

**Comment by mohamedahmedawad93** [comment]
@maizaied @mahmoudHussein @HebaElSobky review ya ged3an :D

**Comment by mohamedahmedawad93** [comment]
@BeshoSmile please review my code

**Comment by mohamedahmedawad93** [comment]
@BeshoSmile review my code

**Comment by mohamedahmedawad93** [comment]
@HebaElSobky 
to test shell:
user1=UserProfile(name='Mohamed',email='1')
user2=UserProfile(name='Amr',email='2')
channel1=Channel(name='cars',description='jkj')
subchannel1=Subchannel(name='sport cars',channel_id=channel1)
attribute1=Attribute(name='color',subchannel_id=subchannel1,weight=1)
choice1=AttributeChoice(attribute_id=attribute1, value='red')
subscription1=Subscription(channel=channel1,sub_channel=subchannel1,parameter=attribute1,choice=choice1)
post1=Post(sub_channel_id=subchannel1,user=user2)

**Comment by mohamedahmedawad93** [comment]
@HebaElSobky 

new shell testing:

from tager_www.models import *
user1=UserProfile(name='Mohamed',email='1@3.com');user1.save()
user2=UserProfile(name='Amr',email='2@3.com');user2.save()
channel1=Channel(name='cars',description='jkj');channel1.save()
subchannel1=Subchannel(name='sport cars',channel_id=channel1);subchannel1.save()
subchannel2=Subchannel(name='SUV',channel_id=channel1);subchannel2.save()
attribute1=Attribute(name='color',subchannel_id=subchannel1,weight=1);attribute1.save()
attribute2=Attribute(name='color',subchannel_id=subchannel2,weight=1);attribute2.save()
choice1=AttributeChoice(attribute_id=attribute1, value='red');choice1.save()
choice2=AttributeChoice(attribute_id=attribute2, value='red');choice2.save()
subscription1=Subscription(channel=channel1,sub_channel=subchannel1,parameter=attribute1,choice=choice1);subscription1.save()
subscription2=Subscription(channel=channel1,sub_channel=subchannel1);subscription2.save()
subscription3=Subscription(channel=channel1);subscription3.save()
subscription4=Subscription(channel=channel1,sub_channel=subchannel2,parameter=attribute2,choice=choice2);subscription4.save()
subscription5=Subscription(channel=channel1,sub_channel=subchannel2);subscription5.save()
channel2=Channel(name='Anaimals',description='jkj');channel2.save()
subchannel3=Subchannel(name='Cats',channel_id=channel2);subchannel3.save()
subchannel4=Subchannel(name='Dogs',channel_id=channel2);subchannel4.save()
attribute3=Attribute(name='age',subchannel_id=subchannel3,weight=1);attribute3.save()
attribute4=Attribute(name='age',subchannel_id=subchannel4,weight=1);attribute4.save()
choice3=AttributeChoice(attribute_id=attribute3, value='2');choice3.save()
choice4=AttributeChoice(attribute_id=attribute4, value='2');choice4.save()
subscription6=Subscription(channel=channel2,sub_channel=subchannel3,parameter=attribute3,choice=choice3);subscription6.save()
subscription7=Subscription(channel=channel2,sub_channel=subchannel3);subscription7.save()
subscription8=Subscription(channel=channel2);subscription8.save()
subscription9=Subscription(channel=channel2,sub_channel=subchannel4,parameter=attribute4,choice=choice4);subscription9.save()
subscription10=Subscription(channel=channel2,sub_channel=subchannel4);subscription10.save()

**Comment by HebaElSobky** [comment]
@mohamedahmedawad93  your scenario has been reviewed :+1: #110
