### ISSUE TITLE
Facebook register and login now working

### ISSUE THREAD

**Issue by ahmedshireef** [DinaSaad/sharesoft-13#172]
@saraismail1234  @nadeembarakat  @mohamedhammad89  @Reem-Sharkawy 
Please review

**Comment by Reem-Sharkawy** [comment]
![Screenshot from 2013-04-28 15:01:02](https://f.cloud.github.com/assets/3513928/435758/c1c4808e-b003-11e2-9cf8-d2eecea35cac.png)

the system crashes when refreshing !
please check the error and push again

**Comment by saraismail1234** [comment]
did u do documentation??
