### ISSUE TITLE
As a user i should add posts to my wish list

### ISSUE THREAD

**Issue by abdelrahmanMaged** [DinaSaad/sharesoft-13#185]
Uml reviewer: @HalaKamal 
Documentation reviewer: @Tharwat7 
Code Reviewer: @BeshoSmile 
Scenario reviewer: @Reem-Sharkawy 
Success scenario:
Logged in user press on wishlist icon on the post receive notification that it is successfully added.

Failure Scenario:
if the user already added that post to wish list he/she will receive notification regarding this

Tasks:
1- Write the views, templates and model 
2- Documentation and sequence diagram
3- Tests

**Comment by Reem-Sharkawy** [comment]
abdo check the issure format 
include your reviewers and the subtasks

**Comment by Reem-Sharkawy** [comment]
and if you started working on your story , label it status-in-progress
otherwise , status-new :D

**Comment by Reem-Sharkawy** [comment]
reviewed

**Comment by HalaKamal** [comment]
tage me when u finish the diagram  @AbdelrahmanAyad
