### ISSUE TITLE
as a user , I should provide my mobile phone number when I click im interested , if I didn't provide it earlier  with (sms verfication)

### ISSUE THREAD

**Issue by maizaied** [DinaSaad/sharesoft-13#186]
reviewers : 
code : Mohamed Awad 
scenario : Heba 
documentation : mahmoud ahmed 

success scenario : 
a user must be logged in then choose a post , press intereste in a popup will apear for entering users number and then press enter , a text msg wil be send to verify the number , and the textbox for entering the number will disspear while another textbox will apear for entering the verficationcode 

failour :
the buyer enters the wrong code , a msg will appear saying please enter the right code , or resend sms

**Comment by maizaied** [comment]
@HebaElSobky  @mahmoudHussein @mohamedahmedawad93  please rewvieww

**Comment by mahmoudHussein** [comment]
@maizaied doc verified and please update the rest of your labels

**Comment by maizaied** [comment]
okay thank u !

**Comment by maizaied** [comment]
@iBebarz  ahmed plz review my sequence digram , ull find it fel drive on gmail :D
