### ISSUE TITLE
As a user, my private number and personal information should not be publically announced on the site unless its specified (optional privacy)

### ISSUE THREAD

**Issue by HebaElSobky** [DinaSaad/sharesoft-13#189]
Success:
A user has his private information on the system however its not visible to the private eye and it becomes visible when another user send him a request for the information then if the seller accepts his info is sent to this buyer.
Failure:
the buyer might not find a request button to request the sellers information , the seller has his phone number hidden but its still seen by the user 

Reviewers:
Documentation Reviewer @mahmoudHussein 
UML/Design Reviewer @maizaied 

Implementation Reviewer @mohamedahmedawad93 
Scenario Reviewer @AbdelrahmanAyad , @Reem-Sharkawy 

Tasks:
C2-21.1 Write the view, templates and model 
C2-21.2 Documentation and sequence diagram
C2-21.3 Tests

**Comment by maizaied** [comment]
@HebaElSobky  the actor doesnt have any activattion bar or dotted , the boxes should have the app name and wat it acceses it example tager_www <<models>> , then show the method name and its paramters in the vieww that is accessed from the view 
check it plz and tagg me aagain

**Comment by maizaied** [comment]
change the other aswell because they r done in the same way

**Comment by HebaElSobky** [comment]
Msh fahma ??

**Comment by maizaied** [comment]
bosii shoffi mine as an example 7atfhmii ts on the drive

**Comment by HebaElSobky** [comment]
I just saw this okay I'll check yours and correct mine!! Thank youu

**Comment by HebaElSobky** [comment]
@maizaied  this is the other one
