### ISSUE TITLE
As a user i should be able to change the type of my account anytime i want through the settings

### ISSUE THREAD

**Issue by HebaElSobky** [DinaSaad/sharesoft-13#190]
Success:
There should be the option to change your user plan and switch from a premium user to a free user and vice verse from the settings.
Failure:
The option to change the user type isn't available inside the site and the user can't change if he wants to.

Reviewers:
Documentation Reviewer @mahmoudHussein 
UML/Design Reviewer @maizaied 

Implementation Reviewer @mohamedahmedawad93 
Scenario Reviewer @AbdelrahmanAyad , @Reem-Sharkawy 

Tasks:
C2-24.1 Write the view and the templates 
C2-24.2 Develop tests
C2-24.3 Draw the sequence diagram
C2-24.4 Documentation

**Comment by abdelrahmanMaged** [comment]
@HebaElSobky we agreed that this point will not be 5 points so cn you please change the label i know that in the backlog it is 5 but we agreed that the estimate will be less than that 
Regards,

**Comment by mohamedahmedawad93** [comment]
@HebaElSobky you forgot to push your account.html

**Comment by mahmoudHussein** [comment]
@HebaElSobky documentation verified just have a small comment though if you can just make C2- heba el sobky- story name that would be great ... but the rest is fine !

**Comment by HebaElSobky** [comment]
@maizaied this is it
