### ISSUE TITLE
As a User i should be able to navigate through Channels and their SubChannels through the side menu

### ISSUE THREAD

**Issue by Tharwat7** [DinaSaad/sharesoft-13#194]
Success:
A User (whether guest or logged in) goes to the homepage and navigates through the different channels and their sub-channels and access them in order to view the posts related to each sub-channel on the navigation menu on the left of the page

Failure:
User fails to find a Channel or Sub-channel that are of his or her interest

Reviewers:
Documentation Reviewer @mahmoudHussein 
UML/Design Reviewer @HalaKamal 
Code Reviewer @BeshoSmile 
Scenario Reviewer @abdelrahmanMaged  
Tasks:
C1-24

**Comment by mahmoudHussein** [comment]
@Tharwat7 tharwat i'm not you reviewer @saraismail1234 is your reviewer
