### ISSUE TITLE
Fix the Base and Main Page

### ISSUE THREAD

**Issue by Tharwat7** [DinaSaad/sharesoft-13#195]
Reviewers:
Documentation Reviewer @mahmoudHussein 
UML/Design Reviewer @HalaKamal 
Code Reviewer @BeshoSmile 
Scenario Reviewer @abdelrahmanMaged

Tasks:
C1-23

**Comment by mahmoudHussein** [comment]
@Tharwat7 i am not you reviewer btw ! @saraismail1234  is your reviewer !

**Comment by BeshoyAtef** [comment]
Verified
