### ISSUE TITLE
Activity log

### ISSUE THREAD

**Issue by mohamedahmedawad93** [DinaSaad/sharesoft-13#210]
As a user i should view my activity log
success scenario:
  1- user should view only his related activities
  2- activities should be sorted according to date

documentation reviewer: @mahmoudHussein 
scenario reviewer: @HebaElSobky 
UML reviewer: @maizaied

**Comment by mahmoudHussein** [comment]
@mohamedahmedawad93 please define the labels

**Comment by mohamedahmedawad93** [comment]
@mahmoudHussein i defined the labels you can review now

**Comment by mahmoudHussein** [comment]
Give me 5 mins and I'll be done with you isa ! I already started !
Sent from my BlackBerry® from Vodafone

-----Original Message-----

**Comment by abdelrahmanMaged** [comment]
@mohamedhammad89 pleease verify my code

**Comment by mohamedhammad89** [comment]
code verified
