### ISSUE TITLE
Improve Profile GUI-ONLY

### ISSUE THREAD

**Issue by BeshoyAtef** [DinaSaad/sharesoft-13#214]

**Comment by mohamedahmedawad93** [comment]
@BeshoSmile kolo tamam bs aldiv bta3 alfriends da5el 3alwish list

**Comment by mohamedahmedawad93** [comment]
@BeshoSmile try height: auto or relative kanet 7aga keda in css format

**Comment by BeshoyAtef** [comment]
ok hashof now

**Comment by mohamedahmedawad93** [comment]
@BeshoSmile code verified

**Comment by BeshoyAtef** [comment]
<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=9K_VTpCUoE2byUVkNvOiK6okblx0Ft8lhl93nwGwATI.eyJlbW
FpbCI6InJlcGx5K2ktMTM3Mjc2NjctOTQ2NDk5NzNiZWUyMTM0Yzg5NjUxYmI3YmViOTY3ZDViYzE5ZTE
zNi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiI5MWNmM2VhOC1jNWFiLTVjNjYtODQ4Yy1lMDk1YWZiYjBkNTkiLCJpc
3N1ZWRfYXQiOiIxMzY5ODQ1NDA2IiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=4d29f5ef-7d
c8-e211-a4c9-c701ce909180&emailType=Invite&sdate=201305291636&utm_source=EmailInv
ite&utm_medium=Email&sendercc=EG&emailLinkType=Logo>

Hi,

Beshoy Atef wants to connect with you.

<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=9K_VTpCUoE2byUVkNvOiK6okblx0Ft8lhl93nwGwATI.eyJlbW
FpbCI6InJlcGx5K2ktMTM3Mjc2NjctOTQ2NDk5NzNiZWUyMTM0Yzg5NjUxYmI3YmViOTY3ZDViYzE5ZTE
zNi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiI5MWNmM2VhOC1jNWFiLTVjNjYtODQ4Yy1lMDk1YWZiYjBkNTkiLCJpc
3N1ZWRfYXQiOiIxMzY5ODQ1NDA2IiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=4d29f5ef-7d
c8-e211-a4c9-c701ce909180&emailType=Invite&sdate=201305291636&utm_source=EmailInv
ite&utm_medium=Email&sendercc=EG&emailLinkType=ProfileThumb>

Beshoy Atef
<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=9K_VTpCUoE2byUVkNvOiK6okblx0Ft8lhl93nwGwATI.eyJlbW
FpbCI6InJlcGx5K2ktMTM3Mjc2NjctOTQ2NDk5NzNiZWUyMTM0Yzg5NjUxYmI3YmViOTY3ZDViYzE5ZTE
zNi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiI5MWNmM2VhOC1jNWFiLTVjNjYtODQ4Yy1lMDk1YWZiYjBkNTkiLCJpc
3N1ZWRfYXQiOiIxMzY5ODQ1NDA2IiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=4d29f5ef-7d
c8-e211-a4c9-c701ce909180&emailType=Invite&sdate=201305291636&utm_source=EmailInv
ite&utm_medium=Email&sendercc=EG&emailLinkType=ProfileName>

Invite sent: 29 May, 2013

Continue
<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=9K_VTpCUoE2byUVkNvOiK6okblx0Ft8lhl93nwGwATI.eyJlbW
FpbCI6InJlcGx5K2ktMTM3Mjc2NjctOTQ2NDk5NzNiZWUyMTM0Yzg5NjUxYmI3YmViOTY3ZDViYzE5ZTE
zNi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiI5MWNmM2VhOC1jNWFiLTVjNjYtODQ4Yy1lMDk1YWZiYjBkNTkiLCJpc
3N1ZWRfYXQiOiIxMzY5ODQ1NDA2IiwidmVyIjoiMSIsInAiOiIzIn0&cnId=88470b98-4248-e011-88
9f-c965259bf186&emailMessageId=4d29f5ef-7dc8-e211-a4c9-c701ce909180&emailType=Inv
ite&sdate=201305291636&utm_source=EmailInvite&utm_medium=Email&sendercc=EG&emailL
inkType=MainCallToAction>

reply+i-13727667-94649973bee2134c89651bb7beb967d5bc19e136-3515278@reply.github.co
m was invited to join SkillPages by Beshoy Atef. To stop receiving emails from
SkillPages click here
<http://www.skillpages.com/i/account/unsubscribe?signedParameters=8n8oUW0ODb0yPmh
CBSsxJZxUZz3A-nzY_w1aGXTjiok.eyJlbWFpbCI6InJlcGx5K2ktMTM3Mjc2NjctOTQ2NDk5NzNiZWUy
MTM0Yzg5NjUxYmI3YmViOTY3ZDViYzE5ZTEzNi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJpc3N1Z
WRfYXQiOiIxMzY5ODQ1NDA2IiwidmVyIjoiMSIsInAiOiIwIn0&emailMessageId=4d29f5ef-7dc8-e
211-a4c9-c701ce909180&emailType=Invite&sdate=201305291636&utm_source=EmailInvite&
utm_medium=Email&sendercc=EG&emailLinkType=Unsubscribe> .

© 2013 SkillPages, Blackrock Business Park, Dublin, Ireland and 228 Hamilton
Avenue, 3rd Floor, Palo Alto, CA 94301.

**Comment by BeshoyAtef** [comment]
<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=nfC3jMYMf-tf12aBu-TQw6xTPCF2VVaNfRSIryYPi3I.eyJlbW
FpbCI6InJlcGx5K2ktMTM3Mjc2NjctOTQ2NDk5NzNiZWUyMTM0Yzg5NjUxYmI3YmViOTY3ZDViYzE5ZTE
zNi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiI5MWNmM2VhOC1jNWFiLTVjNjYtODQ4Yy1lMDk1YWZiYjBkNTkiLCJpc
3N1ZWRfYXQiOiIxMzcwMzkxODg4IiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=0cc9fa14-73
cd-e211-be08-d229661189ee&emailType=InviteFirstReminder&sdate=201306050024&utm_so
urce=EmailInviteFirstReminder&utm_medium=Email&sendercc=EG&emailLinkType=Logo>

Hi,

Beshoy is waiting for you to accept this pending invitation.

<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=nfC3jMYMf-tf12aBu-TQw6xTPCF2VVaNfRSIryYPi3I.eyJlbW
FpbCI6InJlcGx5K2ktMTM3Mjc2NjctOTQ2NDk5NzNiZWUyMTM0Yzg5NjUxYmI3YmViOTY3ZDViYzE5ZTE
zNi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiI5MWNmM2VhOC1jNWFiLTVjNjYtODQ4Yy1lMDk1YWZiYjBkNTkiLCJpc
3N1ZWRfYXQiOiIxMzcwMzkxODg4IiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=0cc9fa14-73
cd-e211-be08-d229661189ee&emailType=InviteFirstReminder&sdate=201306050024&utm_so
urce=EmailInviteFirstReminder&utm_medium=Email&sendercc=EG&emailLinkType=ProfileT
humb>

Beshoy Atef
<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=nfC3jMYMf-tf12aBu-TQw6xTPCF2VVaNfRSIryYPi3I.eyJlbW
FpbCI6InJlcGx5K2ktMTM3Mjc2NjctOTQ2NDk5NzNiZWUyMTM0Yzg5NjUxYmI3YmViOTY3ZDViYzE5ZTE
zNi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiI5MWNmM2VhOC1jNWFiLTVjNjYtODQ4Yy1lMDk1YWZiYjBkNTkiLCJpc
3N1ZWRfYXQiOiIxMzcwMzkxODg4IiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=0cc9fa14-73
cd-e211-be08-d229661189ee&emailType=InviteFirstReminder&sdate=201306050024&utm_so
urce=EmailInviteFirstReminder&utm_medium=Email&sendercc=EG&emailLinkType=ProfileN
ame>

Invite sent: 29 May, 2013

Continue
<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=nfC3jMYMf-tf12aBu-TQw6xTPCF2VVaNfRSIryYPi3I.eyJlbW
FpbCI6InJlcGx5K2ktMTM3Mjc2NjctOTQ2NDk5NzNiZWUyMTM0Yzg5NjUxYmI3YmViOTY3ZDViYzE5ZTE
zNi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiI5MWNmM2VhOC1jNWFiLTVjNjYtODQ4Yy1lMDk1YWZiYjBkNTkiLCJpc
3N1ZWRfYXQiOiIxMzcwMzkxODg4IiwidmVyIjoiMSIsInAiOiIzIn0&cnId=88470b98-4248-e011-88
9f-c965259bf186&emailMessageId=0cc9fa14-73cd-e211-be08-d229661189ee&emailType=Inv
iteFirstReminder&sdate=201306050024&utm_source=EmailInviteFirstReminder&utm_mediu
m=Email&sendercc=EG&emailLinkType=MainCallToAction>

reply+i-13727667-94649973bee2134c89651bb7beb967d5bc19e136-3515278@reply.github.co
m was invited to join SkillPages by Beshoy Atef. To stop receiving emails from
SkillPages click here
<http://www.skillpages.com/i/account/unsubscribe?signedParameters=Mps5BKQ7wV2jMir
JsBbtSA6j9sR9wyL1_wXYdo5MXhM.eyJlbWFpbCI6InJlcGx5K2ktMTM3Mjc2NjctOTQ2NDk5NzNiZWUy
MTM0Yzg5NjUxYmI3YmViOTY3ZDViYzE5ZTEzNi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJpc3N1Z
WRfYXQiOiIxMzcwMzkxODg4IiwidmVyIjoiMSIsInAiOiIwIn0&emailMessageId=0cc9fa14-73cd-e
211-be08-d229661189ee&emailType=InviteFirstReminder&sdate=201306050024&utm_source
=EmailInviteFirstReminder&utm_medium=Email&sendercc=EG&emailLinkType=Unsubscribe>
.

© 2013 SkillPages, Blackrock Business Park, Dublin, Ireland and 228 Hamilton
Avenue, 3rd Floor, Palo Alto, CA 94301.

**Comment by BeshoyAtef** [comment]
<http://www.skillpages.com/i/ftux/emailinvitelanding?signedParameters=Ye0Vxb16wS-
gawbe-4QPbRs4qdXExDBum04ExUfvNgU.eyJlbWFpbCI6InJlcGx5K2ktMTM3Mjc2NjctOTQ2NDk5NzNi
ZWUyMTM0Yzg5NjUxYmI3YmViOTY3ZDViYzE5ZTEzNi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmc
m9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYtYzk2NTI1OWJmMTg2IiwidG8iOiI5MWNmM2VhOC1jNW
FiLTVjNjYtODQ4Yy1lMDk1YWZiYjBkNTkiLCJpc3N1ZWRfYXQiOiIxMzcwOTk2NjQzIiwidmVyIjoiMSI
sInAiOiIzIn0&emailMessageId=be672e48-f3d2-e211-884e-85d1397596ad&emailType=Invite
SecondReminder&sdate=201306120024&utm_source=EmailInviteSecondReminder&utm_medium
=Email&sendercc=EG&emailLinkType=Logo>

Hi,

Beshoy Atef is still waiting to connect with you.

<http://www.skillpages.com/i/ftux/emailinvitelanding?signedParameters=ftux/emaili
nvitelanding?signedParameters=Ye0Vxb16wS-gawbe-4QPbRs4qdXExDBum04ExUfvNgU.eyJlbWF
pbCI6InJlcGx5K2ktMTM3Mjc2NjctOTQ2NDk5NzNiZWUyMTM0Yzg5NjUxYmI3YmViOTY3ZDViYzE5ZTEz
Ni0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYtY
zk2NTI1OWJmMTg2IiwidG8iOiI5MWNmM2VhOC1jNWFiLTVjNjYtODQ4Yy1lMDk1YWZiYjBkNTkiLCJpc3
N1ZWRfYXQiOiIxMzcwOTk2NjQzIiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=be672e48-f3d
2-e211-884e-85d1397596ad&emailType=InviteSecondReminder&sdate=201306120024&utm_so
urce=EmailInviteSecondReminder&utm_medium=Email&sendercc=EG&emailLinkType=Profile
Thumb>

Beshoy Atef
<http://www.skillpages.com/i/ftux/emailinvitelanding?signedParameters=ftux/emaili
nvitelanding?signedParameters=Ye0Vxb16wS-gawbe-4QPbRs4qdXExDBum04ExUfvNgU.eyJlbWF
pbCI6InJlcGx5K2ktMTM3Mjc2NjctOTQ2NDk5NzNiZWUyMTM0Yzg5NjUxYmI3YmViOTY3ZDViYzE5ZTEz
Ni0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYtY
zk2NTI1OWJmMTg2IiwidG8iOiI5MWNmM2VhOC1jNWFiLTVjNjYtODQ4Yy1lMDk1YWZiYjBkNTkiLCJpc3
N1ZWRfYXQiOiIxMzcwOTk2NjQzIiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=be672e48-f3d
2-e211-884e-85d1397596ad&emailType=InviteSecondReminder&sdate=201306120024&utm_so
urce=EmailInviteSecondReminder&utm_medium=Email&sendercc=EG&emailLinkType=Profile
Name>

Invite sent: 29 May, 2013

Continue
<http://www.skillpages.com/i/ftux/emailinvitelanding?signedParameters=Ye0Vxb16wS-
gawbe-4QPbRs4qdXExDBum04ExUfvNgU.eyJlbWFpbCI6InJlcGx5K2ktMTM3Mjc2NjctOTQ2NDk5NzNi
ZWUyMTM0Yzg5NjUxYmI3YmViOTY3ZDViYzE5ZTEzNi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmc
m9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYtYzk2NTI1OWJmMTg2IiwidG8iOiI5MWNmM2VhOC1jNW
FiLTVjNjYtODQ4Yy1lMDk1YWZiYjBkNTkiLCJpc3N1ZWRfYXQiOiIxMzcwOTk2NjQzIiwidmVyIjoiMSI
sInAiOiIzIn0&emailMessageId=be672e48-f3d2-e211-884e-85d1397596ad&emailType=Invite
SecondReminder&sdate=201306120024&utm_source=EmailInviteSecondReminder&utm_medium
=Email&sendercc=EG&emailLinkType=MainCallToAction>

reply+i-13727667-94649973bee2134c89651bb7beb967d5bc19e136-3515278@reply.github.co
m was invited to join SkillPages by Beshoy Atef. To stop receiving emails from
SkillPages click here
<http://www.skillpages.com/i/account/unsubscribe?signedParameters=mWs3mDf-XgWo11M
1IFVqi-HDqwRjtyPqxK7-pr_4kgM.eyJlbWFpbCI6InJlcGx5K2ktMTM3Mjc2NjctOTQ2NDk5NzNiZWUy
MTM0Yzg5NjUxYmI3YmViOTY3ZDViYzE5ZTEzNi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJpc3N1Z
WRfYXQiOiIxMzcwOTk2NjQzIiwidmVyIjoiMSIsInAiOiIwIn0&emailMessageId=be672e48-f3d2-e
211-884e-85d1397596ad&emailType=InviteSecondReminder&sdate=201306120024&utm_sourc
e=EmailInviteSecondReminder&utm_medium=Email&sendercc=EG&emailLinkType=Unsubscrib
e> .

© 2013 SkillPages, Blackrock Business Park, Dublin, Ireland and 228 Hamilton
Avenue, 3rd Floor, Palo Alto, CA 94301.
