### ISSUE TITLE
As a user ,I should view the people i interacted with in my profile.

### ISSUE THREAD

**Issue by mahmoudHussein** [DinaSaad/sharesoft-13#221]
when a user logs in and checks his account profile he should be able to view the list of people he interacted (bought or sold stuff to) and this should be viewed in a box in the profile page.

@maizaied @HebaElSobky @mohamedahmedawad93

**Comment by mahmoudHussein** [comment]
@Tharwat7 please check my documentation

**Comment by mahmoudHussein** [comment]
@Tharwat7 @HebaElSobky please review my branch !!

**Comment by Tharwat7** [comment]
@mahmoudHussein 
Please fix what i told u 2

**Comment by mahmoudHussein** [comment]
@Tharwat7 fix what ? care to elaborate more ?

**Comment by Tharwat7** [comment]
@look at the comments in the document -____-

**Comment by mahmoudHussein** [comment]
@Tharwat7 what document ?

**Comment by mahmoudHussein** [comment]
@maizaied please review my diagram its on the drive

**Comment by maizaied** [comment]
@mahmoudHussein you need to changed the top mm box and right the app name and wat ur accessing example : tager_www <<templates>> , then when the user clicks this should call a method in the views u have to wite the name and its parameters mesh discribtion and when it returns the list show thhis a dotted line cuz its a return , plz revise the sequence digram and show it to me again 
thank u :D

**Comment by mahmoudHussein** [comment]
@maizaied i don't understand what you want in the first part but as for the second part about calling the method i did and the method takes no attributes so don't worry. so please call me because i don't understand what to do in the first part.

**Comment by maizaied** [comment]
did u correct it ?

**Comment by mahmoudHussein** [comment]
Yes I did please check it on the email :D
Sent from my BlackBerry® from Vodafone

-----Original Message-----

**Comment by maizaied** [comment]
checked !
