### ISSUE TITLE
Story c2-7

### ISSUE THREAD

**Issue by mohamedahmedawad93** [DinaSaad/sharesoft-13#55]
As c2 I should provide the channel by which a user could subscribe to by checking if user is verified and can subscribe to channels, allowing user to subscribe to channels and sub channels directly and allowing user to subscribe using parameters.
@mahmoudHussein @HebaElSobky @maizaied

**Comment by BeshoyAtef** [comment]
THIS SHOULD BE CLOSED
@mahmoudHussein  @HebaElSobky  @maizaied 

REVIEW AND CLOSE !!!
