### ISSUE TITLE
As a user i should be able to post in a specific channel

### ISSUE THREAD

**Issue by abdelrahmanMaged** [DinaSaad/sharesoft-13#56]

**Comment by abdelrahmanMaged** [comment]
I verified the scenario as there are no scenarios in this sprint good luck

**Comment by BeshoyAtef** [comment]
Please Check my comments on the pull request

**Comment by BeshoyAtef** [comment]
THIS SHOULD BE CLOSED 
PLease @Tharwat7 @HalaKamal  @AbdelrahmanAyad  CLOSE IT
