### ISSUE TITLE
add table user-network

### ISSUE THREAD

**Issue by saraismail1234** [DinaSaad/sharesoft-13#58]
this table will be created so the user's friends (specially imported friends) would be stored in it, when the user presses import friends from facebook.

**Comment by saraismail1234** [comment]
@Reem-Sharkawy  @mohamedhammad89 @nadeembarakat @iBebarz

**Comment by BeshoyAtef** [comment]
@Reem-Sharkawy @mohamedhammad89 @nadeembarakat @iBebarz 

THIS SHOULD BE CLOSED
