### ISSUE TITLE
as c3 I should enable Facebook Connection to Import friends

### ISSUE THREAD

**Issue by saraismail1234** [DinaSaad/sharesoft-13#60]
after the FB connection is already established, the user can import his friends list on facebook to our website.

@Reem-Sharkawy @mohamedhammad89 @nadeembarakat @iBebarz

**Comment by BeshoyAtef** [comment]
@Reem-Sharkawy  , @mohamedahmedawad93  @nadeembarakat @iBebarz 

REVIEW AND CLOSE !@!!
