### ISSUE TITLE
viewing the rate the seller button - dependency

### ISSUE THREAD

**Issue by mahmoudHussein** [DinaSaad/sharesoft-13#61]
As a buyer i should be able to view " rate the sellers" button on the post where i bought from. the button should only be viewed (appear) by the people that the buyer bought from.

**Comment by mahmoudHussein** [comment]
@maizaied @HebaElSobky @mohamedahmedawad93

**Comment by BeshoyAtef** [comment]
Why this is STILL OPEN ?
@mahmoudHussein

**Comment by BeshoyAtef** [comment]
@maizaied , @HebaElSobky  Please Review and CLOSE

**Comment by mahmoudHussein** [comment]
@BeshoSmile it will be closed now ...no worries
