### ISSUE TITLE
Adding User_Network Table

### ISSUE THREAD

**Issue by nadeembarakat** [DinaSaad/sharesoft-13#62]
Adding User_Network Table which contains User's Friends who are  imported from his fb friends list

**Comment by nadeembarakat** [comment]
@Reem-Sharkawy  @saraismail1234  @iBebarz  @mohamedhammad89

**Comment by BeshoyAtef** [comment]
@Reem-Sharkawy @saraismail1234 @mohamedhammad89 

THIS SHOULD BE CLOSED
