### ISSUE TITLE
Create the (I'm interested) relationship tables -

### ISSUE THREAD

**Issue by Tharwat7** [DinaSaad/sharesoft-13#64]
@BeshoSmile @HalaKamal @AbdelrahmanAyad 

Please review my code

**Comment by abdelrahmanMaged** [comment]
There are no scenarios in this layer so the scenario is verified

**Comment by BeshoyAtef** [comment]
amr i cant find the files , nor the branch

**Comment by Tharwat7** [comment]
@BeshoSmile  i have added them they are online please check again
