### ISSUE TITLE
As C2, I should provide Sub-channels to the channels

### ISSUE THREAD

**Issue by HebaElSobky** [DinaSaad/sharesoft-13#66]
As C2, I should provide sub-channels to the existing channels to which the user can subscribe to as well as know how to link such function to the admin so that the admin can add a sub-channel when requested to.

@mahmoudHussein @maizaied @mohamedahmedawad93 
Any notes

**Comment by BeshoyAtef** [comment]
SHOULD BE CLOSED !!

**Comment by HebaElSobky** [comment]
close #66
