### ISSUE TITLE
As a seller/Buyer , I can specify special attributes to help me guide through my search 

### ISSUE THREAD

**Issue by mohamedhammad89** [DinaSaad/sharesoft-13#91]
success:
the user is directed to the advanced page , user starts to refine the channels and choosing one , the paramters for the chosen channel appears on the left , user fills in the paramters  ( check boxes  and within slider ) and the relevant posts appear in the center , a button above the paramters specifies the whether the user si searching for other users , the searching speed meet the user's expectations 

failure:

the user doesnot find any results , he will be notified to refine the paramteres , 

reviewers:

documentation reviewer : @saraismail1234 
UML reviewer : @iBebarz 
implementation reviewer : @BeshoSmile 
scenario reviewers : @Reem-Sharkawy  @nadeembarakat

**Comment by BeshoyAtef** [comment]
@mohamedhammad89 Please check the mail and follow the Issue format

**Comment by Reem-Sharkawy** [comment]
mohamed please , try to ammed the frond end in order to be able to test

**Comment by Reem-Sharkawy** [comment]
reviwed
