### ISSUE TITLE
As a user I should be able to regisster through an email account  [User sign-up with an e-mail account]

### ISSUE THREAD

**Issue by maizaied** [DinaSaad/sharesoft-13#93]
doc : @mahmoudHussein  scenrio : @HebaElSobky  code : @mohamedahmedawad93 

sucess : [*Navigate to the website's welcome page
*Click on "Sign up with e-mail" button
*User is redirected to the sign up page where he enters his name, e-mail and password in textfields, where the e-mail is verified for correctness, and password verified for strength.
*User press Sign-up
*User is redirected to a page where he receives a "Thank you" message and is asked to verify his e-mail.]

failure : [*Wrong/existing e-mail format, validation message not correctly sent.
*Didn’t fill the mandatory field and tries to sign-up
*Passwords don’t match]

**Comment by maizaied** [comment]
@mahmoudHussein  @HebaElSobky @mohamedahmedawad93  plz review me and guys el view 7amlha pull request 3ashan i pushed enter withooyt the number soo review it bardoo

**Comment by BeshoyAtef** [comment]
maio :+1:

**Comment by maizaied** [comment]
@mahmoudHussein  @mohamedahmedawad93 @HebaElSobky  plz review

**Comment by BeshoyAtef** [comment]
#128

**Comment by maizaied** [comment]
@mahmoudHussein  @mohamedahmedawad93  @HebaElSobky  please review me :D

**Comment by maizaied** [comment]
@mohamedahmedawad93  some stuff wont work without mahmouds login so when ur revieing take it

**Comment by maizaied** [comment]
@mahmoudHussein  @HebaElSobky  @mohamedahmedawad93 please review :D

**Comment by mohamedahmedawad93** [comment]
@maizaied your code is verified

**Comment by HebaElSobky** [comment]
@maizaied  scenario has been verified :+1:

**Comment by maizaied** [comment]
@HebaElSobky  @mohamedahmedawad93  please review me

**Comment by maizaied** [comment]
please review me @HebaElSobky @mohamedahmedawad93
