### ISSUE TITLE
As an unverified user i should be able to browse through the website pages however i can't post or comment unless i verify my account

### ISSUE THREAD

**Issue by maizaied** [DinaSaad/sharesoft-13#95]
reviewers doc :@mahmoudHussein  scenrio :  @HebaElSobky  code review : @mohamedahmedawad93 

success :browse through the site seeing everything like a normal user except that i cant post or comment 
 failure : having access for commenting on a post or posting

**Comment by BeshoyAtef** [comment]
@maizaied Please check the mail and follow the Issue format

**Comment by maizaied** [comment]
@mahmoudHussein @HebaElSobky @mohamedahmedawad93  please review
