### ISSUE TITLE
A user can add post in a specific channel

### ISSUE THREAD

**Issue by abdelrahmanMaged** [DinaSaad/sharesoft-13#96]
@HalaKamal @Tharwat7 @BeshoSmile 
Success Story:
[A logged in user:
*Press the "Add post" button in the "Home" page.
*User gets redirected to "Create post" page
*User fills in the obligatory post attributes (form will refuse to submit of left blank):
-Name
-Picture
-Price
*User fills in the extra post attributes
*Press "Submit" button, gets alert that post added successfully, redirected to post page (click on this link)]
Failure story:
 user cannot submit the post unless the mandatory fields are filled.
If the user did not fill the mandatory fields , ( user is notified that he has to fill those fields )
if the user is not logged in , if he still wants to post , he will be notified to log in or to verify his email.
if the user is free he must not have more than three active posts in the same time

**Comment by BeshoyAtef** [comment]
@abdelrahmanMaged Please check the mail and follow the Issue format

**Comment by AbdelrahmanAyad** [comment]
@Tharwat7 @BeshoSmile @Reem-Sharkawy 
Please review my code you can find it attached on your email as i sent due to some issue in my git account

**Comment by HalaKamal** [comment]
@abdelrahmanMaged  yits only one actor not two , and the arrows must point to top of the life time, and point 6 is wrong direction
