### ISSUE TITLE
C2- As a buyer/seller i should be able to manage my profile and personalise it 

### ISSUE THREAD

**Issue by HebaElSobky** [DinaSaad/sharesoft-13#97]
Success story:
1. profile pic: /enter my own profile/ choose the upload image button on the top left corner of the picture/ amenu will appear/ choos ethe image to upload/ enter/ receive notification/ profile updated with the new pic
2. Personal info: choose the setting button on the top right corner of the page/ choose account settings/ edit the personal info in the specified fields/click save button at the bottom/ profile updated with recent info (info requested: 1. DOB/ user will choose the DOB form the calendar/some restrictions will be considered/ 2. Gender/user will choose gender from dropdown menu or radio button/ 3. Personal Info: /edit peronsal extra info (depending on user) in required textfields (such as works at, interests, status))
3. Status: /enter my own profile/ click on the top right textfield with “enter your own status”/ enter your status/ press enter

Failure:
1. Profile pic: /enter my own profile/ choose the upload image button on the top left corner of the picture/ amenu will appear/ choos ethe image to upload/ enter/ image size or format not supported, or user uploads a diff filetype.
2. Personal info: choose the setting button on the top right corner of the page/ choose account settings/ edit the personal info in the specified fields/click save button at the bottom/ entered wrong info OR entered a DOB that hasent yet passed
3. Status: /enter my own profile/ click on the top right textfield with “enter your own status”/ enter an empty status OR press empty spaces OR passes the limit of the characters

Document reviewer: @mahmoudHussein 
UML reviewer: @maizaied 
Code reviewer: @mohamedahmedawad93

**Comment by BeshoyAtef** [comment]
@HebaElSobky  Please check the mail and follow the Issue format

**Comment by mahmoudHussein** [comment]
happy can you please hook the pull request to the issue so i can review you ?!

**Comment by HebaElSobky** [comment]
ohh okaay

**Comment by HebaElSobky** [comment]
thank u

**Comment by mohamedahmedawad93** [comment]
@HebaElSobky i verified your code
