### ISSUE TITLE
C2- As a user i should be able to update my personal information

### ISSUE THREAD

**Issue by HebaElSobky** [DinaSaad/sharesoft-13#98]
A user can update his/her personal information on the profile such as phone number, age, working place 

Success Story:
*Click on the settings button on the top left corner of the page
*Click on "Account settings"
*Edit the personal information in the specified field
    -DOB is from a calendar with some restrictions
    -Gender will be selected from a drop down list (or a radio button)
    -Other personal information in text fields such as "works at" or ....
*Click the "Save" button
*User is then notified that his profile page has been updated with the new information

Failure Story:
If the user deletes the field in any mandatory field by mistake, the system refuses to save personal information page without the 
mandatory fields.

Reviewers:
Document reviewer: @mahmoudHussein 
UML reviewer: @maizaied  
Code reviewer: @mohamedahmedawad93

**Comment by BeshoyAtef** [comment]
@HebaElSobky Please check the mail and follow the Issue format

**Comment by HebaElSobky** [comment]
@Reem-Sharkawy @AbdelrahmanAyad review

**Comment by HebaElSobky** [comment]
@AbdelrahmanAyad please review the scenario and take into consideration the 3line in the subscriptions.js #98
